### ISSUE TITLE
Distinct not working as I expect

### ISSUE THREAD

**Issue by STashakkori** [nilsmartel/string#2]
Running the following command:
echo "test1 test2 test3 test2" | string distinct

Gives this output:
test1 test2 test3 test2

Is this by design?

I can confirm that this works:
cat file.txt | string district

Output:
test1
test2
test3

**Comment by nilsmartel** [comment]
It is per design, though it might be that the design isn't a well thought out, as I'd like it.

The `string` cli only distincts lines at the moment, though it might make sense to create `--words` flag, to switch the behaviour.

Is there a use case, for which that would be useful to you?

**Comment by STashakkori** [comment]
Ah ok! The tool is great. Line functionality is perfect don't need removing duplicate token functionality at the moment so all good. For some reason though, the token functionality was what I intuitively expected first.  Not sure why. You know my friend I think its because of the usage actually:

"Output the set of input strings without repitions, in order"
There is a slight typo also. But I think I misread this to think literally in order, ie back to back

Thank you so much for your assistance. I am enjoying this tool a lot

**Comment by nilsmartel** [comment]
I am deeply happy to hear, people (other than me) are actually using this. I think it's very nice. The typo will be fixed and I think it's rather trivial to add new functionality. Stay healthy and thank you for the compliment
