### ISSUE TITLE
Replace adds a newline to the end of the text

### ISSUE THREAD

**Issue by STashakkori** [nilsmartel/string#5]
Hello again my friend. Replace adds an extra newline that should not be at the end of the text or file.

For example:
cat test123.txt
Output:
test1
test2
test3
test2
test2
test2

cat test123.txt | string replace --match test2 --with test0
test1
test0
test3
test0
test0
test0
\n

Is there a way to prevent this? Thank you

**Comment by nilsmartel** [comment]
Thank you for opening an issue here! I really appreciate it 👍🏼 
That behavoir is unexpected and should be fixed per default

**Comment by nilsmartel** [comment]
Fixed in version 0.3.1
